### ISSUE TITLE
Add more forums

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/Website#11]
I just checked the admin page of the forum. And I think we can add another forum:

- **Support**
_Support for NPG related issues like application errors and more._

  

-  **Bug Tracking**
 _If you found something odd let us know here._

- **Servers issues**
_Community support for server configuration issues._

- **Development and customization**
_Get help and feedback for everything development and customization related_

**Comment by sbillard** [comment]
Bug tracking and support are done on the GitHub repository. 
GitHub is designed for this, PhpBB is not. The other forums can be made if you wish. However, experience from the Zenphoto forum's 10+ years is that people just don't pay attention to the distinction and treat the forum as a single thread.

**Comment by By-oussef** [comment]
I just added two forums, with two tutorials can you consult them:
https://netphotographics.org/forum/index.php

https://netphotographics.org/forum/viewtopic.php?f=11&t=37

https://netphotographics.org/forum/viewtopic.php?f=13&t=36
