### ISSUE TITLE
Update to the latest version of php

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/Website#13]
I check the version of the server since the administration of phpbb and phph version is used is 7.1 I think we can update to the latest version of php because it is safer and faster.

**Comment by sbillard** [comment]
One cannot upgrade to a version of PHP not supported by the hosting service.. Besides what benefit is there in doing this?

Please let me advise you that this flood of requests are bordering on being on being considered a spam attack. Implementations take time and money. There needs to be a real need or benefit to justify them. 

This is an open source project h. Feel free to contribute. If you are not intending to contribute a solution perhaps there inee.
