### ISSUE TITLE
Use zpbootstrap for netphotographics.org

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/Website#14]
zpBootstrap is a responsive theme for Zenphoto. zpBoostrap uses and configures it's own colorbox/slideshow and modal plugins.
more the menu is at the top.

**Scripts used:**

Bootstrap (HTML, CSS, and JS toolkit for Responsive WebSite)
Flexslider (a fully responsive jQuery slider plugin)
FancyBox (lightbox jQuery plugin for displaying images. Touch enabled, responsive and fully customizable)
AddThis (snippet to add sharing tools to your site)
Inifite Scroll (jQuery plugin that automatically adds the next page)
script for navigation with the arrow keys on single news pages and images pages
The theme supports the following ZenPhoto plugins:

cacheManager, comment_form, contact_form, dynamic-locale, favoritesHandler, flag_thumbnail, GoogleMap (colorbox option not supported), openstreetmap (new), rating, register_user, user_login-out, zenpage

**Comment by sbillard** [comment]
I personally do not really like that theme.
