### ISSUE TITLE
Add About Page 

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/Website#18]

**Comment by sbillard** [comment]
Just what do you mean by this and how would it differ from the opening page?

**Comment by By-oussef** [comment]
netPhotoGraphics™ (formerly ZenPhoto20)
Releases
The current "official" release (and all previous ones) may be found at Releases

Tagged releases include one or more single file install packages for ease of installation. Instructions for its use are included in the download. (Interim install packages are created to incorporate minor updates to the software.)

netPhotoGraphics will be updated incrementally via GitHub. We will tag releases when new features are added or significant bugs are fixed. There will not be a fixed release cycle nor a "Development" stream.

Our development methodology is structured to insure that the master branch of the repository remains stable. So if you wish to have the most recent fixes you can safely install the master branch. There is no means to include the single file install with the branch, so they are available only on tagged releases.

About netPhotoGraphics
netPhotoGraphics is a standalone CMS for multimedia focused websites. Our focus lies on being easy to use and having all the features there when you need them (but out of the way if you do not.)

netPhotoGraphics features support for images, video and audio formats, a news section (blog), and custom pages to run entire websites.

This makes netPhotoGraphics the ideal CMS for personal websites of illustrators, artists, designers, photographers, film makers and musicians.

netPhotoGraphics was created with a fork of the Zenphoto repository at the time of the Zenphoto 1.4.6 release. It spent the first four years of its life as ZenPhoto20. In 2018 the name was changed to netPhotoGraphics. The intent of the branching was to clean up the years of detritus that the original code accumulated. At the same time the we modernized the software, the support process, and the integration of third party contributions.

Support
Problems may be reported and features requested via repository issues

Discussions are hosted on the netPhotoGraphics Forum

**Comment by sbillard** [comment]
This is nothing more than the readme.md file on GitHub. I am not inclined to replicate content. It is much too hard to maintain when the same content is in multiple places. There is a link to the repository, so this text is readily viewable.
