### ISSUE TITLE
Bar content cookies

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/Website#7]
Hello Sbillard, I discovered on the site that when a user arrives on netphotographics.net he arrives on a page or he must accept cookies. It would be best to remove this and replace with a bar at the bottom of the "Accept cookies" screen like this: https://cookieconsent.insites.com/

Demo : https://cookieconsent.insites.com/app/themes/insites-cookie-consent/examples/example-4-opt-out.html

**Comment by sbillard** [comment]
The page he lands on is the site policy page and the user must accept the policy before he can use the site. This is per the EU GDPR rules. Part of the policy is the use of cookies. But cookies are only part of the site policy so cookie consent is insufficient.
