### ISSUE TITLE
Add support for native image lazy-loading for the web

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/Website#9]
Hi @sbillard

Can you read this article : https://addyosmani.com/blog/lazy-loading/
The loading attribute
The loading attribute allows a browser to defer loading offscreen images and iframes until users scroll near them. loading supports three values:

lazy: is a good candidate for lazy loading.
eager: is not a good candidate for lazy loading. Load right away.
auto: browser will determine whether or not to lazily load.

**Comment by sbillard** [comment]
Lazyimage is now enabled on the site.
